name: Swift

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.2.0'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
